### ISSUE TITLE
Allow people to sponsor Mathesar

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#54]
- [x] Sign up for Open Collective
- [x] Sign up for GitHub Sponsors
- [x] Add `FUNDING.yml` to main repo
- [ ] Add `FUNDING.yml` to all public repos
- [ ] Re-review and fill out Open Collective profile 
- [ ] Re-review and fill out GitHub Sponsors profile 
- [x] #83

**Comment by Pursottam6003** [comment]
Where to do this in my forked repository @kgodey could you please explain

**Comment by kgodey** [comment]
@Pursottam6003 This issue is not related to the code. It's also restricted to maintainers (see the label), and not open for contribution.
