### ISSUE TITLE
Set up website live demo integration

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#6]
- [ ] Link to live demo from navigation
- ~~Provide a link back to the website from the live demo~~ (Skipped, see https://github.com/centerofci/mathesar-website/issues/6#issuecomment-1372841977).

**Comment by pavish** [comment]
@kgodey @ghislaineguerin 

> Link to live demo from navigation

When user clicks 'Live Demo', I intend it to open a new browser tab and open the live demo there. It won't open the live demo in the same page.

In this scenario, do we need point 2.

> Provide a link back to the website from the live demo

If we do need this, I'd like a quick UX design. I would like to know how the link should look and work, and the behaviour on different viewport sizes.

**Comment by kgodey** [comment]
> I intend it to open a new browser tab and open the live demo there. It won't open the live demo in the same page.

That's fine, make sure to include the external link icon in the nav so that it's clear it opens in a new page. I think we can skip the link back to the website.
