### ISSUE TITLE
Mailing list improvements

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-website#66]
- [ ] With the new additions, our mailing list signup section at the end of each page is a bit clunky. We should explore an alternative design for it.
- [ ] We also need to add the checkboxes to https://mathesar.org/mailing-list.html

**Comment by seancolsen** [comment]
I was thinking about this issue today as I was trying to figure out how to navigate from the home page to the mailing list sign-up.

- It might be nice to have a link to the mailing list sign-up somewhere in the header.
    - It could go to the left of the GitHub link.
    - Or maybe another link under "Community" (in which case we'd have separate menu items for "Discussion mailing list" and "Product announcement mailing list" or something)

- We have these two forms

    ![image](https://user-images.githubusercontent.com/42411/221014840-ea451e51-9ffd-41a6-8627-287a0bca1ca3.png)

    ![image](https://user-images.githubusercontent.com/42411/221014947-4b03b1f8-996a-46b5-ab84-6a896daba10e.png)

    It would be nice to make these consistent. I suggest starting with the blue box form, but then replacing _"Stay updated on our open source and cloud development"_ with _"Join Our Mailing List"_. Then we could use that same UI for the widget and for the page.

**Comment by seancolsen** [comment]
```yaml
- Home
- How it Works
  - Software Engineer
  - Non-Technical Expert
  - FAQ
- Live Demo
- Install
- Hosted
- Community
  - GitHub
  - Matrix (Chat)
  - Discussion Mailing Lists
  - Product Announcements Mailing List
  - Wiki
  - Roadmap
```

**Comment by kgodey** [comment]
@seancolsen Thanks for the suggestions! I'll think about them and create additional issues as needed.

**Comment by kgodey** [comment]
Some nav items have been moved to dropdowns and I added the mailing list to the nav in https://github.com/centerofci/mathesar-website/commit/0f7ba32a7c7990c7fa0a624382c6d12834758f92, so I'm considering this done.
