### ISSUE TITLE
Menu too wide for responsive breakpoint

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar-website#75]
Looks like the top level menu got a new item since we last adjusted the responsive breakpoint to hide the menu. Now it has weird wrapping at some viewport widths:

![image](https://user-images.githubusercontent.com/42411/222424416-dea41157-0204-4c57-8ffb-662e7b4857ee.png)

We should either:

- Rearrange the menu items, removing some from the top level

    _or_

- Adjust the breakpoint to hide the menu for wider viewports

**Comment by kgodey** [comment]
@seancolsen Let's adjust the breakpoint for now.

**Comment by seancolsen** [comment]
We [discussed](https://matrix.to/#/!OBFOMvPciDqjqcoSUO:matrix.mathesar.org/$LDEfaKNB04DIpTzmwxs4IkPFX-LQS88H82SH61XfWEc?via=matrix.mathesar.org&via=matrix.org) this and decided to resolve it by re-arranging the menu items. @kgodey will handle it.
