### ISSUE TITLE
align footer  content  to the center

### ISSUE THREAD

**Issue by SainiAditya1** [centerofci/mathesar-website#79]

**Comment by SainiAditya1** [comment]
@kgodey  I want to work on this..

**Comment by kgodey** [comment]
@SainiAditya1 Please add more details to the issue. I do not know what "align footer to the center" means.

**Comment by SainiAditya1** [comment]
https://user-images.githubusercontent.com/116535947/223308329-56b290a8-b0a0-430d-9d61-fd9df2914ef9.jpeg

**Comment by SainiAditya1** [comment]
@kgodey , I am talking about this..

**Comment by SainiAditya1** [comment]
@kgodey , I think it looks better in the center..
